apiVersion: v1
kind: Pod
metadata:
  name: striversity-stack
  labels:
    name: striversity-stack
spec:
  containers:
  - name: redis
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379
