apiVersion: v1
kind: Pod
metadata:
  name: striversity-stack2
  labels:
    name: striversity-stack
spec:
  containers:
  - name: server
    image: striversity/using-k8s:server-02
    env:
      - name: "REDIS_URL"
        value: "redis:6379"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
