apiVersion: apps/v1
kind: Deployment
metadata:
  name: asrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asrv
  template:
    metadata:
      labels:
        app: asrv
    spec:
      containers:
      - name: asrv
        image: striversity/using-k8s:asrv
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
