apiVersion: v1
kind: Service
metadata:
  name: asrv2
spec:
  selector:
    app: asrv2
  ports:
  - name: asrv-port
    port: 8080
    targetPort: 8080
  - name: nginx-port
    port: 80
    targetPort: 80
