apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
  namespace: development
  labels:
    name: my-pod-1
spec:
  containers:
  - name: my-pod-1
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
