apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-nfs
spec:
  resources:
    requests:
      storage: 200Mi
  storageClassName: slow
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
